server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'phucle'
    password: 'password'
    url: jdbc:postgresql://postgres:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka